### ISSUE TITLE
unigram frequency file?

### ISSUE THREAD

**Issue by hardyqr** [recski/wordsim#23]
Hi! Is it possible to make the used [freq_file](https://github.com/recski/wordsim/blob/9887a10412b686e0beb0540ac8d026c9a878f6cc/configs/default.cfg#L4) available for adding 4lang features? Or have I missed anything and it is actually not needed? 

Thanks for the help!

**Comment by recski** [comment]
@hardyqr Thanks for pointin this out! I'm not sure why that line in the config got commented out, maybe @Eszti has some memory?

Anyway, I put the frequency file [here](http://sandbox.hlt.bme.hu/~recski/umbc_webbase.unigram_freq.min50) for now and I'll look into it next week. A check that all resources and configs are still working has been long overdue anyway...

**Comment by recski** [comment]
I pushed a number of bugfixes, most due to updated APIs of dependencies (sklearn, gensim). The frequency file you mentioned was not necessary to run the default configuration, but let me know if you experience otherwise! And thanks again for pointing this out!
